target: bin
home: crossstitch.md
site: crossstitch

commands:
    before:
        - [rsync, -av, resources, bin]
        - [python, build.py, 2017, pages/2017.md, resources/2017]
        - [python, build.py, 2018, pages/2018.md, resources/2018]
        - [python, build.py, 2019, pages/2019.md, resources/2019]
        - [python, build.py, 2020, pages/2020.md, resources/2020]
        - [python, build.py, pyxstitch, pages/pyxstitch.md, resources/pyxstitch]
        - [python, build.py, 2020, crossstitch.md, resources/current, --preamble, README.md, --latest]

css:
    - crossstitch.css

pages:
    directory: pages
    includes:
        "1x3.png": "1x3.png"
        "2x5.png": "2x5.png"
        "3x5.png": "3x5.png"
        "3x6p.png": "3x6p.png"
        "3x7.png": "3x7.png"
        "4x7p.png": "4x7p.png"
        "5x9.png": "5x9.png"
        "5x9p.png": "5x9p.png"
    side:
        tooling: tooling
    top:
        "fonts": "fonts"
        "pyxstitch": "pyxstitch"
        "2020": "2020"
        "2019": "2019"
        "2018": "2018"
        "2017": "2017"

tasks:
    enable: false
